language: python
dist: trusty

python:
  - "2.7"

sudo: required

cache:
  pip: true

addons:
  apt:
    packages:
      - libxml2-dev
      - libxmlsec1-dev

before_install:
  - sudo locale-gen en_US en_US.UTF-8 pt_BR.UTF-8
  - sudo dpkg-reconfigure locales

install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/pip install -r test-requirements.txt

script:
  - bin/python setup.py flake8
  - bin/python setup.py lint
  - bin/python setup.py test
