language: python
dist: trusty

python:
  - "2.7"

sudo: required

cache:
  pip: true

addons:
  apt:
    packages:
      - libxml2-dev
      - libxmlsec1-dev
      - python-dev
      - libffi-dev
      - libxslt1-dev
      - libssl-dev
      - libxmlsec1-dev

env:
  - LINT="1" FLAKE="0" TEST="0"
  - LINT="0" FLAKE="1" TEST="0"
  - LINT="0" FLAKE="0" TEST="1"

before_install:
  - sudo locale-gen en_US en_US.UTF-8 pt_BR.UTF-8
  - sudo dpkg-reconfigure locales

install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/pip install -r test-requirements.txt

script:
  - sh travis_run_script.sh
